os: linux

language: c

compiler: gcc

addons:
  apt:
    packages:
    - valgrind

before_script:
  - pip install --user cpp-coveralls

script:
  - cmake -D CMAKE_BUILD_TYPE:String="Coverage" .
  - make
  - make test
  - ctest -T MemCheck
  - coveralls --include src/  --gcov-options '\-lp'
