os: linux

language: c

compiler: gcc

addons:
  apt:
    packages:
    - cmake
    - valgrind

before_script:
  - pip install --user cpp-coveralls

script:
  - cmake -D CMAKE_BUILD_TYPE:String="Debug" .
  - make
  - make test
  - ctest -T MemCheck
